# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-28 18:10
from __future__ import unicode_literals

import archive.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('pdf', models.FileField(null=True, upload_to=archive.models.pdf_path)),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('page_number', models.IntegerField()),
                ('scanned_img', models.ImageField(null=True, upload_to=archive.models.tif_path)),
                ('image', models.ImageField(null=True, upload_to=archive.models.jpg_path)),
                ('pdf', models.FileField(null=True, upload_to=archive.models.pdf_path)),
                ('text', models.TextField()),
                ('issue', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='archive.Issue')),
            ],
            options={
                'ordering': ['-date', 'page_number'],
            },
        ),
    ]
