# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-08 22:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('sponsor', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('page_number', models.IntegerField()),
                ('text', models.TextField()),
                ('issue', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='archive.Issue')),
            ],
            options={
                'ordering': ['-date', 'page_number'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='page',
            unique_together=set([('date', 'page_number')]),
        ),
    ]
