# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-28 19:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='date',
            field=models.DateField(unique=True),
        ),
    ]
