# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-29 01:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0002_auto_20160928_1936'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='sponsor',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
