# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-18 22:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0002_issue_pdf_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='issue',
            options={'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='page',
            name='processed_datetime',
            field=models.DateTimeField(null=True),
        ),
    ]
