# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-18 00:29
from __future__ import unicode_literals

import archive.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0002_page_scan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='scan',
            field=models.ImageField(null=True, upload_to=archive.models.scan_path),
        ),
    ]
