# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-18 00:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0003_auto_20160918_0029'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='text',
            field=models.TextField(default='test'),
            preserve_default=False,
        ),
    ]
