# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-26 19:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0003_auto_20161018_2212'),
    ]

    operations = [
        migrations.CreateModel(
            name='Month',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sponsor', models.CharField(max_length=200, null=True)),
                ('date', models.DateField(unique=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='issue',
            options={'ordering': ['date']},
        ),
        migrations.AlterModelOptions(
            name='page',
            options={'ordering': ['date', 'page_number']},
        ),
        migrations.RemoveField(
            model_name='issue',
            name='sponsor',
        ),
    ]
