# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-21 17:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0004_page_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page',
            old_name='page',
            new_name='page_number',
        ),
        migrations.RenameField(
            model_name='page',
            old_name='scan',
            new_name='scanned_img',
        ),
    ]
