# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-26 19:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0004_auto_20161026_1909'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='month',
            options={'ordering': ['date']},
        ),
        migrations.AddField(
            model_name='month',
            name='available',
            field=models.BooleanField(default=False),
        ),
    ]
