# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-22 04:44
from __future__ import unicode_literals

import archive.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0006_auto_20160921_1908'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page',
            options={'ordering': ['-date', 'page_number']},
        ),
        migrations.AddField(
            model_name='issue',
            name='pdf',
            field=models.FileField(null=True, upload_to=archive.models.pdf_path),
        ),
        migrations.AddField(
            model_name='page',
            name='pdf',
            field=models.FileField(null=True, upload_to=archive.models.pdf_path),
        ),
    ]
